"""Base types for sandbox execution.

The SandboxExecutor protocol is the abstraction layer between
CodeVerifier and the actual isolation backend (Docker, sbx, Shuru).
The control plane should not care which backend runs the command —
it cares about policy, evidence, exit code, and logs.

Security note (v0.4.0-alpha stabilization):
  The current proxy-based network mode (BEST_EFFORT_PROXY) is NOT a
  security boundary. It only affects clients that respect HTTP_PROXY /
  HTTPS_PROXY environment variables. It does NOT prevent raw socket
  egress, DNS bypasses, or direct IP connections. The default is
  NetworkMode.DISABLED. Use ENFORCED_GATEWAY only when you have
  validated the Docker --internal network + gateway container setup.
"""

import secrets
import textwrap
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


class NetworkMode(str, Enum):
    """Sandbox network isolation mode.

    DISABLED (default): no network access at all. The safest mode.
        Use this for all untrusted code execution.

    BEST_EFFORT_PROXY: sets HTTP_PROXY / HTTPS_PROXY env vars to route
        through an SNI egress proxy. NOT a security boundary — clients
        that ignore proxy env vars (raw sockets, direct IP) can bypass
        it. Use only with trusted code that respects proxy conventions.

    ENFORCED_GATEWAY: the candidate container runs on a Docker
        --internal network with no direct internet access. All egress
        goes through a gateway/proxy container that enforces the
        allow-list at the network level. EXPERIMENTAL — not validated
        with bypass tests in all environments. Fail-closes to
        --network none if the gateway network cannot be created.
        Requires Docker.
    """

    DISABLED = "disabled"
    BEST_EFFORT_PROXY = "best_effort_proxy"
    ENFORCED_GATEWAY = "enforced_gateway"


# Environment variable name carrying the per-execution verification nonce.
# The harness reads this and prints ``VT_PASS_<nonce>`` only if the test
# block completes without raising. Candidate code cannot forge the marker
# because it does not know the nonce (it is generated by the caller and
# passed through the sandbox environment, not embedded in the script source).
VT_TEST_NONCE_ENV = "VT_TEST_NONCE"
VT_TEST_PASS_PREFIX = "VT_PASS_"


def generate_test_nonce() -> str:
    """Generate a fresh 16-char hex nonce for one test execution."""
    return secrets.token_hex(8)


def build_test_harness(code: str, tests: str) -> tuple[str, str]:
    """Build the sandbox test-harness script and its verification nonce.

    The harness wraps candidate ``code`` in a try/except (IMPORT_ERROR on
    failure), then runs ``tests`` in a second try/except. Only if the test
    block completes *without* raising does it read the nonce from the
    ``VT_TEST_NONCE`` environment variable and print
    ``VT_PASS_<nonce>`` to stdout.

    The nonce is NOT embedded in the script source — it is read from the
    environment at runtime — so candidate code cannot print the success
    marker by guessing it. The caller must pass ``env={VT_TEST_NONCE_ENV:
    nonce}`` to the executor and record the returned nonce in the
    ``ExecutionResult.evidence`` for the verifier to check.

    Returns:
        ``(script, nonce)`` where ``script`` is the full Python program to
        execute and ``nonce`` is the hex string the verifier should look for
        (formatted as ``VT_PASS_<nonce>``) in stdout.
    """
    nonce = generate_test_nonce()
    code_clean = textwrap.dedent(code).strip()
    tests_clean = textwrap.dedent(tests).strip()
    script = (
        "import os, sys, traceback\n"
        "try:\n"
        + textwrap.indent(code_clean, "    ") + "\n"
        "except Exception as e:\n"
        "    print(f'IMPORT_ERROR: {e}')\n"
        "    sys.exit(1)\n"
        "try:\n"
        + textwrap.indent(tests_clean, "    ") + "\n"
        f"    print('{VT_TEST_PASS_PREFIX}'"
        f" + os.environ['{VT_TEST_NONCE_ENV}'])\n"
        "except AssertionError as e:\n"
        "    print(f'ASSERTION_FAILED: {e}')\n"
        "    sys.exit(1)\n"
        "except Exception as e:\n"
        "    print(f'TEST_ERROR: {e}')\n"
        "    traceback.print_exc()\n"
        "    sys.exit(1)\n"
    )
    return script, nonce


@dataclass
class ExecutionResult:
    """Result of executing code in a sandbox.

    Attributes:
        exit_code: process exit code (0 = success).
        stdout: captured stdout.
        stderr: captured stderr.
        timed_out: True if the execution hit the timeout limit.
        executor: name of the executor backend that ran this.
        sandbox_name: name of the sandbox/container if applicable.
        duration_ms: wall-clock execution time in milliseconds.
        evidence: additional structured evidence (diff summary, hashes, etc.).
        error: None if no infrastructure error, else a description.
    """
    exit_code: int
    stdout: str
    stderr: str
    timed_out: bool = False
    executor: str = "unknown"
    sandbox_name: Optional[str] = None
    duration_ms: int = 0
    evidence: Dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None

    @property
    def succeeded(self) -> bool:
        """True if exit_code == 0 and not timed out and no
        infrastructure error."""
        return (
            self.exit_code == 0
            and not self.timed_out
            and self.error is None
        )


@runtime_checkable
class SandboxExecutor(Protocol):
    """Protocol for isolated code execution backends.

    Implementations:
      - DockerSandboxExecutor: runs code in a Docker container with
        network isolation, memory limits, read-only filesystem.
      - DockerSbxExecutor: runs code in an sbx microVM (heavier weight,
        full VM isolation, private Docker daemon).
      - LocalSubprocessExecutor: UNSAFE — runs code directly on host.
        Only for development/testing where Docker is not available.

    The protocol is async so backends that need I/O (Docker API, sbx CLI)
    can implement it naturally.
    """

    name: str

    async def execute(
        self,
        script: str,
        *,
        timeout: float = 10.0,
        network: bool = False,
        memory_limit: str = "128m",
        env: Optional[Dict[str, str]] = None,
    ) -> ExecutionResult:
        """Execute a Python script in an isolated environment.

        Args:
            script: Python source code to execute.
            timeout: maximum execution time in seconds.
            network: if True, allow network access. Default False.
                Network access should be opt-in, never default.
            memory_limit: memory limit for the execution environment.
            env: optional environment variables to set.

        Returns:
            An :class:`ExecutionResult` with stdout, stderr, exit code,
            and timing information.
        """
        ...

    async def execute_tests(
        self,
        code: str,
        tests: str,
        *,
        timeout: float = 10.0,
        network: bool = False,
        memory_limit: str = "128m",
    ) -> ExecutionResult:
        """Execute unit tests against candidate code.

        Args:
            code: the candidate Python code to test.
            tests: Python test code that imports/uses the candidate.
            timeout: maximum execution time in seconds.
            network: if True, allow network access. Default False.
            memory_limit: memory limit for the execution environment.

        Returns:
            An :class:`ExecutionResult`. Exit code 0 with the nonce marker
            (``VT_PASS_<nonce>``) in stdout means tests passed. The expected
            marker is stored in ``result.evidence["test_nonce"]``.
        """
        ...

    def is_available(self) -> bool:
        """Check if this executor backend is available on the current system.

        Returns:
            True if the backend can be used (Docker installed, sbx
            installed, etc.), False otherwise.
        """
        ...

    async def cleanup(self) -> None:
        """Clean up any resources (containers, temp files, etc.)."""
        ...
